services:
  app_base: &app_base  
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - .env

  app1:
    <<: *app_base
    container_name: app1
    environment:
      - PORT=9001
      - REDIS_HOST=redis

  app2:
    <<: *app_base
    container_name: app2
    environment:
      - PORT=9002
      - REDIS_HOST=redis
      
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "9000:9000"
    depends_on:
      - app1
      - app2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

volumes:
  redis-data:
    driver: local
