services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: url_shortener
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    ports:
      - "9000:9000"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
    driver: local
 